### ISSUE TITLE
ne_10m_admin_0_countries shapefile missing ISO_A2 and ISO_A3 for certain countries

### ISSUE THREAD

**Issue by poezn** [nvkelso/natural-earth-vector#131]
ISO_A2 and ISO_A3 codes are missing for certain countries in the 10m political shapefile. They're present in the 50m shapefile, though.

Most important examples: France, Kosovo, Norway, and about a dozen smaller/newer/disputed countries.

**Comment by nvkelso** [comment]
The ISO codes are on the Natural Earth admin level feature (sovereignty,
country, map unit, or map sub-unit) that matches the ISO definition. If
you're not finding it in one level, look in the next up or down.

It sounds like you're asking for a fuzzy ISO code instead of a strict ISO
code concordance / crosswalk. That seems like a useful feature.

If the 10m and 50m files aren't matching that's an error and should be
fixed. But they're built off the same source table so that would be
surprising.

**Comment by poezn** [comment]
Got it. Thanks for the reply.

The discrepancy between the 10m and 50m shapefile is likely due to the different version. 10m is v3.1.0 and 50m is v2.0.0.

I'm still not 100% clear on France and Norway, given FR/FRA and NO/NOR doesn't exist on any of the (sovereignty, country, map unit, or map sub-unit) levels. 

Finally, it would be great if this was documented somewhere, along with some meta data about what the columns in the shapefile mean. I'm happy to help out if I can.

**Comment by kernc** [comment]
:+1: to have France and Norway define ISO_A3, ISO_A3 and ISO_N3 in 10m_admin0 (etc.).

How is this fuzzy? Wikipedia [lists FR and NO](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) as from the standard and doesn't mention any ambiguity.

**Comment by nvkelso** [comment]
Closing in favor of #12.
